# Generated by Django 6.0 on 2026-02-14 12:25

import django.db.models.deletion
import project.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('description', models.TextField()),
                ('problem_statement', models.TextField(blank=True)),
                ('key_features', models.JSONField(blank=True, default=list)),
                ('my_role', models.TextField(blank=True)),
                ('technical_challenges_solutions', models.JSONField(blank=True, default=list)),
                ('architectural_overview', models.JSONField(blank=True, default=dict)),
                ('future_enhancements', models.JSONField(blank=True, default=list)),
                ('live_demo_url', models.URLField(blank=True, max_length=2048, validators=[project.validators.validate_optional_https_url])),
                ('source_code_url', models.URLField(blank=True, max_length=2048, validators=[project.validators.validate_optional_https_url])),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('in_progress', 'In Progress'), ('planned', 'Planned')], db_index=True, max_length=20)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('category', models.CharField(blank=True, choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('database', 'Database'), ('tool', 'Tool'), ('other', 'Other')], default='other', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Technologies',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/%Y/%m/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='project.project')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='technologies',
            field=models.ManyToManyField(blank=True, related_name='projects', to='project.technology'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['-created_at'], name='project_pro_created_efdcd3_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status', '-created_at'], name='project_pro_status_7bf47d_idx'),
        ),
    ]
